# GateGuard: Importers: workflow/executor.py, session/engine.py, decompose/detector.py, tests. Affected API: exports ProgressEvent, ProgressCallback, LoggingProgressCallback, CompositeProgressCallback, emit_*. Data schemas: none. User instruction: Phase 6 — wire progress callbacks, expose via core __init__.

from .agent_loop import AgentLoop, LoopStatus, LoopTool, LoopToolResult, LoopTrace
from .client import DualStackClient, MLXClient
from .config import (
    DEFAULT_GATEWAY_URL,
    DEFAULT_LOCAL_MODEL,
    DualModelConfig,
    ModelConfig,
    ModelRouter,
    ModelStack,
    OfflineConfig,
    OfflineMode,
    RoutingStrategy,
    get_model_config,
)
from .hooks import (
    GuardBridge,
    HookAction,
    HookDecision,
    HookEvent,
    HookHandler,
    HookRegistry,
    audit_log,
    dangerous_cmd_guard,
    default_registry,
    path_guard,
    secret_scrub,
)
from .progress import (
    CompositeProgressCallback,
    LoggingProgressCallback,
    ProgressCallback,
    ProgressEvent,
    emit_complete,
    emit_error,
    emit_progress,
    emit_start,
)
from .safe_writer import SafeWriter, UnsafePathError

__all__ = [
    "MLXClient",
    "DualStackClient",
    "AgentLoop",
    "LoopTool",
    "LoopToolResult",
    "LoopTrace",
    "LoopStatus",
    "HookEvent",
    "HookAction",
    "HookDecision",
    "HookHandler",
    "HookRegistry",
    "GuardBridge",
    "default_registry",
    "path_guard",
    "dangerous_cmd_guard",
    "secret_scrub",
    "audit_log",
    "SafeWriter",
    "UnsafePathError",
    "DEFAULT_LOCAL_MODEL",
    "DEFAULT_GATEWAY_URL",
    "ModelConfig",
    "DualModelConfig",
    "ModelRouter",
    "ModelStack",
    "OfflineConfig",
    "OfflineMode",
    "RoutingStrategy",
    "get_model_config",
    "ProgressEvent",
    "ProgressCallback",
    "LoggingProgressCallback",
    "CompositeProgressCallback",
    "emit_start",
    "emit_progress",
    "emit_complete",
    "emit_error",
]
